global using FluentResults;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Ecommerce.Authorization.Models;
global using Ecommerce.Authorization.Data.DTO;
global using Ecommerce.Authorization.Services;
global using Ecommerce.Authorization.Data.Requests;
global using System.ComponentModel.DataAnnotations;