version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq-service
    networks:
    - ecommerce-bridge
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      retries: 5
      interval: 5s
      timeout: 30s

  ecommerce-authorization:
    image: ecommerce-authorization:1.0
    container_name: ecommerce-authorization
    networks:
      - ecommerce-bridge
    ports:
      - 8080:80

networks:
  ecommerce-bridge:
    driver: bridge
