version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: rabbitmq-service
    networks:
    - ecommerce-bridge
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      retries: 5
      interval: 5s
      timeout: 30s

  mysql:
    image: mysql:8.3.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      retries: 5
      interval: 5s
      timeout: 30s

volumes:
  mysql-data:

networks:
  ecommerce-bridge:
    driver: bridge
