# docker-compose --project-name "backend" up -d
version: "3.9"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-database
    restart: unless-stopped
    networks:
      - ecommerce-bridge
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      retries: 5
      interval: 5s
      timeout: 30s

  ecommerce-api:
    image: ecommerce-api
    container_name: ecommerce-api
    networks:
      - ecommerce-bridge
    environment:
      - AzureStorage:ConnectionString=""
      - AzureStorage:Container=""
    ports:
      - 7105:8080
    depends_on:
      - mysql

  ecommerce-authorization:
    image: ecommerce-authorization
    container_name: ecommerce-authorization
    networks:
      - ecommerce-bridge
    environment:
      - AdminInfo:Password=""
      - EmailSettings:From=""
      - EmailSettings:Password=""
      - EmailSettings:SmtpServer=""
      - EmailSettings:Port=1
      - Twilio:SID=""
      - Twilio:AuthToken=""
      - Twilio:PhoneNumber=""
    ports:
      - 7252:8080
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - ecommerce-bridge
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - ecommerce-bridge
    ports:
      - 3003:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

volumes:
  mysql-data:
  prom_data:

networks:
  ecommerce-bridge:
    driver: bridge
