global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: ecommerce-api
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
        - "ecommerce-api:8080"
  - job_name: ecommerce-authorization
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
        - "ecommerce-authorization:8080"
  - job_name: ecommerce-order-api
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
        - "ecommerce-order-api:8080"
